// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbgxpepadbjlalrpboar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZ3hwZXBhZGJqbGFscnBib2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTgzNTQsImV4cCI6MjA2NTI3NDM1NH0.wdqPB1otGWUk9Rxll0iA94N_VB3ftVEslGC0I6xttnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);